# Generated by Django 3.0.6 on 2022-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
